name: Build the app for Android and iOS

  # CI for MapSwipe app
  #
  # This runs on each push, and does different things depending on the branch and tags of the current commit
on: [push]

jobs:

  check-syntax:
    name: Validate code format and types before building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '16.1.0'
      - name: Install javascript dependencies
        uses: bahmutov/npm-install@v1
      - name: Lint the code
        run: yarn lint
      - name: Check typing of code
        run: yarn flow
      - name: Lint JSON translation files
        run: yarn lintJson

  release-android:
    name: Build and release Android app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '16.1.0'
      - name: Install javascript packages
        uses: bahmutov/npm-install@v1
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.3'
      - name: Jetify react files
        run: yarn jetifier
      - name: Increase filesystem inotify watch limit
        run: sudo sysctl fs.inotify.max_user_watches=524288
      - name: Build dev APK
        run: yarn buildDev

  release-ios:
    name: Build and release iOS app
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '16.1.0'
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.3'
      - name: Install Fastlane
        run: bundle install
      - name: Install javascript packages
        uses: bahmutov/npm-install@v1
