name: Build the app for Android and iOS

  # CI for MapSwipe app
  #
  # This runs on each push, and does different things depending on the branch and tags of the current commit
on: [push]

jobs:

  check-syntax:
    name: Validate code format and types before building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '16.1.0'
      - name: Install javascript dependencies
        run: yarn install --frozen-lockfile
      - name: Lint the code
        run: yarn lint
      - name: Check typing of code
        run: yarn flow


  release-android:
    name: Build and release Android app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '8.12'
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.x'

  release-ios:
    name: Build and release iOS app
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.x'
      - name: Install Fastlane
        run: bundle install
      - name: Install packages
        run: yarn install
