name: Build the app for Android and iOS

  # CI for MapSwipe app
  #
  # This runs on each push, and does different things depending on
  # the branch and tags of the current commit.
  #
  # Secrets come from environment variables from github.
  # Files containing secrets are base64 encoded, and their content
  # loaded from a secret env var.

on: [push]

jobs:

  check-syntax:
    name: Validate code format and types before building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '16.1.0'
      - name: Install javascript dependencies
        uses: bahmutov/npm-install@v1
      - name: Lint the code
        run: yarn lint
      - name: Check typing of code
        run: yarn flow
      - name: Lint JSON translation files
        run: yarn lintJson

  release-android:
    name: Build and release Android app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '16.1.0'
      - name: Install javascript packages
        uses: bahmutov/npm-install@v1
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.3'
      - name: Decode sentry.properties
        env:
          SENTRY_PROPERTIES: ${{ secrets.FILE_SENTRY_PROPERTIES }}
        run: echo "$SENTRY_PROPERTIES" | base64 -d > ./android/sentry.properties
      - name: Decode google-services.json
        env:
          FILE_ANDROID_GOOGLE_SERVICES_DEV: ${{ secrets.FILE_ANDROID_GOOGLE_SERVICES_DEV }}
        run: echo "$FILE_ANDROID_GOOGLE_SERVICES_DEV" | base64 -d > ./android/app/src/dev/google-services.json
      - name: Decode the dev release keystore file
        # passwords and secrets used for decrypting this keystore file
        # MAPSWIPE_RELEASE_STORE_FILE=mapswipe-dev-release-key.keystore
        # MAPSWIPE_RELEASE_KEY_ALIAS=mapswipe-dev-key-alias
        # MAPSWIPE_RELEASE_STORE_PASSWORD=xxx
        # MAPSWIPE_RELEASE_KEY_PASSWORD=xxx
        # All vars are taken from actions env vars, prefixed with ORG_GRADLE_PROJECT_
        # See https://docs.gradle.org/5.6.4/userguide/build_environment.html#sec:project_properties
        env:
          FILE_ANDROID_DEV_RELEASE_KEYSTORE: ${{ secrets.FILE_ANDROID_DEV_RELEASE_KEYSTORE }}
        run: echo "$FILE_ANDROID_DEV_RELEASE_KEYSTORE" | base64 -d > ./android/app/mapswipe-dev-release-key.keystore
      - name: Jetify react files
        run: yarn jetifier
      - name: Increase filesystem inotify watch limit
        run: sudo sysctl fs.inotify.max_user_watches=524288
      - name: Build dev APK
        env:
          ORG_GRADLE_PROJECT_MAPSWIPE_RELEASE_KEY_ALIAS: ${{ secrets.ORG_GRADLE_PROJECT_MAPSWIPE_RELEASE_KEY_ALIAS }}
          ORG_GRADLE_PROJECT_MAPSWIPE_RELEASE_KEY_PASSWORD: ${{ secrets.ORG_GRADLE_PROJECT_MAPSWIPE_RELEASE_KEY_PASSWORD }}
          ORG_GRADLE_PROJECT_MAPSWIPE_RELEASE_STORE_FILE: ${{ secrets.ORG_GRADLE_PROJECT_MAPSWIPE_RELEASE_STORE_FILE }}
          ORG_GRADLE_PROJECT_MAPSWIPE_RELEASE_STORE_PASSWORD: ${{ secrets.ORG_GRADLE_PROJECT_MAPSWIPE_RELEASE_STORE_PASSWORD }}
        run: yarn buildDev

  release-ios:
    name: Build and release iOS app
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '16.1.0'
      - name: Install javascript packages
        uses: bahmutov/npm-install@v1
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.3'
      - name: Install Fastlane
        run: bundle install
